/*
 * Сервис баннеров
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BannerIdDeleteRequest struct {

	// Идентификаторы тэгов
	TagIds *[]int32 `json:"tag_ids,omitempty"`

	// Идентификатор фичи
	FeatureId *int32 `json:"feature_id,omitempty"`

	// Содержимое баннера
	Content *map[string]interface{} `json:"content,omitempty"`

	// Флаг активности баннера
	IsActive *bool `json:"is_active,omitempty"`
}

// AssertBannerIdDeleteRequestRequired checks if the required fields are not zero-ed
func AssertBannerIdDeleteRequestRequired(obj BannerIdDeleteRequest) error {
	return nil
}

// AssertBannerIdDeleteRequestConstraints checks if the values respects the defined constraints
func AssertBannerIdDeleteRequestConstraints(obj BannerIdDeleteRequest) error {
	return nil
}
