/*
 * Сервис баннеров
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type BannerGet201Response struct {

	// Идентификатор созданного баннера
	BannerId int32 `json:"banner_id,omitempty"`
}

// AssertBannerGet201ResponseRequired checks if the required fields are not zero-ed
func AssertBannerGet201ResponseRequired(obj BannerGet201Response) error {
	return nil
}

// AssertBannerGet201ResponseConstraints checks if the values respects the defined constraints
func AssertBannerGet201ResponseConstraints(obj BannerGet201Response) error {
	return nil
}
